import Footer from "../../components/Footers/Footer"
import "../../styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">

      <body>
        {children}

      </body>
      <Footer />

    </html>
  )
}
