import IndexNavbar from "@/components/Navbars/IndexNavbar";
import "@/styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="min-h-screen">
      <IndexNavbar />
      {children}
    </div>
  );
}
